
#===============================================================================
# tex2pdf
#===============================================================================

#' Convert .tex files to a .pdf output.
#'
#' \code{tex2pdf} takes a single .tex file or a vector of .tex files, a single 
#' .pdf filename, an optional character string representing the directory where the 
#' output .pdf file will be written to, and an optional boolean representing
#' whether the output .pdf file should be oriented vertically or horizontally. 
#' A wrapper .tex file with the name "filename".tex is generated and embedded
#' with all of the .tex filenames passed to the \code{texfiles} argument. This 
#' wrapper .tex file is then converted to a .pdf file with the name "filename".tex
#' via the unix command \code{pdflatex}. \code{tex2pdf} may be used to convert
#' regression tables and other tables generated by packages such as \code{xtable}
#' and \code{stargazer} to a .pdf output file without needing to manually create
#' and convert a wrapper .tex file to a .pdf output.
#'
#' @param texfiles Single character filepath or vector of character filepaths to .tex files.
#' @param filename Single character filepath ending in .pdf.
#' @param directory Single character filepath to the desired output directory.
#' @param horizontal Boolean representing whether output .pdf file should be aligned 
#'   horizontally or vertically.
#'
#' @return Output .pdf file.
#'
#' @examples 
#' 
#' lm1 <- lm(X ~ Y, data)
#' lm2 <- lm(X ~ Y + Z, data)
#' 
#' # Create two seperate latex tables, one for each regression.
#' stargazer(lm1, out = paste0(dir, "lm1.tex"))
#' stargazer(lm2, out = paste0(dir, "lm2.tex"))
#' 
#' # Output the two latex tables into the same .pdf file.
#' tex2pdf(
#'   texfiles = c(
#'     paste0(dir, "lm1.tex"),
#'     paste0(dir, "lm2.tex")
#'   ),
#'   filename = paste0(dir, "tables.pdf") ,
#'   directory = paste0(dir, "output_tables/"),
#'   horizontal = FALSE
#' )
#' 

#-------------------------------------------------------------------------------
# tex2pdf
#-------------------------------------------------------------------------------

#' @export

tex2pdf <- function(texfiles, filename, directory = NULL, horizontal = FALSE) {
  
  orig_dir <- getwd()
  
  # Input validation.
  texfile_exts <- lapply(texfiles, function(x) substr(x, nchar(x) - 3, nchar(x)))
  filename_ext <- substr(filename, nchar(filename) - 3, nchar(filename))
  filename_tex <- paste0(substr(filename, 1, nchar(filename) - 4), ".tex")

  if (any(texfile_exts != ".tex")) {
    stop(" * all strings in texfiles must end in .tex")
  }

  if (length(filename) > 1) {
    stop(" * only one filename may be listed, .tex output is written to one PDF")
  }

  if (filename_ext != ".pdf") {
    stop(" * filename must end in .pdf")
  }
  
  if (!is.null(directory)) {
    if (is.character(directory) != TRUE) {
      stop(" * directory must be string representing the path to a directory")
    }
  }
  
  if (any(filename_tex %in% texfiles)) {
    stop(" * filename must have unique name that is different from all of the
           names in texfiles")
  }
  
  texlist <- vector(mode = "list", length = length(texfiles))

  if (horizontal == FALSE) {
    for (i in 1:length(texfiles)) {
      texlist <- append(texlist, paste0("\\input{", texfiles[i], "}"))  
    }
  }
  
  if (horizontal == TRUE) {
    for (i in 1:length(texfiles)) {
      texlist <- append(texlist, paste0("\\begin{landscape} \\input{", texfiles[i], "} \\end{landscape}"))  
    }
  }

  texbody = c("\\documentclass[8pt]{article}",
              "\\usepackage[margin=0.5in]{geometry}",
              "\\usepackage{lscape}",
              "\\usepackage{booktabs}",
              "\\usepackage{subcaption}",
              "\\usepackage{caption}",
              "\\captionsetup{labelformat=empty}",
              "\\usepackage{multirow}",
              "\\usepackage{longtable}",
              "\\usepackage[table]{xcolor}",
              "\\usepackage{dcolumn}",
              "",
              "\\begin{document}",
              "\\pagenumbering{gobble}",
              texlist,
              "\\end{document}")
  
  if (!is.null(directory)) setwd(directory)
  
  texbody <- unlist(texbody)
  write(texbody, filename_tex)
  
  system_call <- paste0('system("pdflatex ', filename_tex, '")')
  eval(parse(text = system_call))
  
  system("rm *.aux *.log")
  
  if (!is.null(directory)) setwd(orig_dir)
  
}

#===============================================================================
# tslp
#===============================================================================

#' Create a time series line plot in ggplot.
#'
#' \code{tslp} takes a data frame, the name of the variable that will be plotted
#' on the x-axis, one or multiple names of the variables that will be plotted on
#' the y-axis, one or multiple y-axis labels, a vector representing the placement
#' of the legend, a single value or vector of values representing line width, and
#' a title, x label, y label, and caption. Metaprogramming is used to convert 
#' these arguments into a ggplot call in the form of a character string. This 
#' character string is printed to console and the ggplot call is evaluated via
#' the \code{eval} command.
#'
#' @param texfiles 
#' @param df Character string representating a data frame object in the Global Environment.
#' @param x Character string representing a column in the \code{df} data frame object.
#' @param y Character string or vector of character strings representing columns 
#' @param labels Character vector of line labels corresponding the columns specified
#'   in the \code{y} argument.
#' @param colors Character vector of colors corresponding to the columns specified
#'   in the \code{y} and \code{labels} arguments.
#'   in the \code{df} data frame object.
#' @param legend.position Numeric vector representing legend placement.
#' @param lwd Numeric vector of line widths for each line specified in the 
#'   \code{y} argument.
#' @param title Character vector used to title the plot.
#' @param xlab Character vector used to label the x-axis of the plot.
#' @param ylab Character vector used to label the y-axis of the plot.
#' @param caption Character vector used to create the caption of the plot.
#' 
#' @return Plot rendered in ggplot.
#'
#' @examples 
#' 
#' tslp(
#'   df = "weather_data",
#'   x = "date",
#'   y = c("outside_temp", "inside_temp"),
#'   labels = c("Outside Temperature", "Inside Temperature"),
#'   colors = c("blue", "red"),
#'   legend.position = c(0.15, 0.90),
#'   lwd = c(0.8, 1),
#'   title = "Outdoor and Indoor Temperature",
#'   xlab = "Date",
#'   ylab = "Temperature",
#'   caption = c(
#'     "Sample period is June to August.
#'     Temperature is measured at the daily frequency."
#'   )
#' )
#' 

#-------------------------------------------------------------------------------
# tslp
#-------------------------------------------------------------------------------

#' @export

tslp = function(df, x, y, labels, colors, legend.position = c(.05, .85), lwd = 0.6, 
                title = "", xlab = "", ylab = "", caption = "") {
  
  if (!is.character(df)) stop("insert data frame name as a character string, ex: df = 'gdp_data'")
  if (!is.character(x))  stop("insert name of x axis column as a character string, ex: 'x = 'forecast_date'")
  if (!is.character(y))  stop("insert name of y axis columns as a vector of character strings, ex: y = c('gdp', 'inflation')")
  if (!length(y) == length(colors)) stop("number of colors must equal the number of y axis columns")

  # data and aes x call
  head = paste0("ggplot(data = ", df, ", aes(x = ", x, ")) + ")
   
  # geom_line calls
  body = vector(mode = 'character', length = length(y))
  for (i in 1:length(y)) {
    body[[i]] = paste0("geom_line(aes(y = ", y[[i]], ", 
                       colour = '", labels[[i]], "'), lwd = ", lwd[[i]], ") +")
  }
  body = paste(body, collapse = " ")
  
  # convert breaks, colors, legend.position to vector call
  breaks = paste0("c('", paste0(labels, collapse = "', '"), "')")
  colors = paste0("c('", paste0(colors, collapse = "', '"), "')")
  legend.position = paste0("c('", paste0(legend.position, collapse = "', '"), "')")
  
  # scale, labs, theme call
  tail = paste0("scale_color_manual(breaks = ", breaks, ", values = ", colors,
              ") + labs(title = '", title, "', x = '", xlab, "', y = '", ylab,
              "', colour = NULL, caption = '", caption, 
              "') + theme_light() + theme(legend.position = ", legend.position, ")")
  
  call = paste(head, body, tail, collapse = " ")
  cat(call)
  eval(parse(text = call))
  
}
